/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.diploma

import com.google.gson.Gson
import com.google.gson.JsonParser
import com.intellij.openapi.project.Project
import com.intellij.util.io.delete
import com.intellij.util.io.write
import org.jetbrains.kotlin.psi.KtBlockExpression
import org.jetbrains.kotlin.psi.KtClassBody
import org.jetbrains.kotlin.psi.KtElement
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.nio.file.Files

class Pipeline(project: Project) {
    private val decoder = Kind2Psi(project)

    fun generateFile(): KtElement {
        val file = decoder.decode("BOX_TEMPLATE")
        walk(file, file)

        return file
    }

    private fun KtElement.append(new: KtElement): KtElement {
        if (this is KtBlockExpression || this is KtClassBody) {
            val rightBrace = node.lastChildNode
            node.addChild(new.node, rightBrace)
            return this.children.last() as KtElement
        }

        return add(new) as KtElement
    }

    private fun walk(file: KtElement, current: KtElement) {
        // autogenerated children (e.g. Body in function)
        if (current.children.isNotEmpty()) {
            current.children.filterIsInstance(KtElement::class.java).forEach { walk(file, it) }
            return
        }

        while (true) {
            try {
                val jsonDatasetSample = extractPaths(file, current).json()
                val predictedNode = predictNode(jsonDatasetSample.toIntegerDatasetSample())
                val newChild = current.append(decoder.decode(predictedNode))

                if (!newChild.isTerminal()) {
                    walk(file, newChild)
                }
            } catch (e: AfterLast) {
                break
            }
        }
    }

    private fun String.toIntegerDatasetSample(): String {
        val i2s = File("/home/tihonovcore/diploma/kotlin/idea/tests/org/jetbrains/kotlin/diploma/out/integer/string2integer.json").readText()
        val string2integer = JsonParser.parseString(i2s).asJsonObject

        val sample = Gson().fromJson(this, DatasetSample::class.java)
        return listOf(
            IntegerDatasetSample(
                sample.leafPaths.map { path -> path.map { node -> string2integer[node]!!.asInt } },
                sample.rootPath.map { node -> string2integer[node]!!.asInt },
                sample.indexAmongBrothers,
                444 //TODO: unused, but model expects
            )
        ).json()
    }

    private fun KtElement.isTerminal(): Boolean {
        //TODO: add other terminals
        //TODO: continue is terminal?? what is `contunue@loop`?
        return node.elementType.toString() in listOf("INTEGER_CONSTANT", "REFERENCE_EXPRESSION", "OPERATION_REFERENCE", "CONTINUE")
    }

    private fun predictNode(jsonDatasetSample: String): String {
        val file = Files.createTempFile("dataset", ".json")
        file.write(jsonDatasetSample)

        // call `predict.py`
        val predict = "/home/tihonovcore/diploma/model/predict.py"
        val dataset = file.toAbsolutePath().toString()

        val process = Runtime.getRuntime().exec("python3 $predict --json_path=$dataset")
        process.waitFor()

        // return result
        val result = BufferedReader(InputStreamReader(process.inputStream)).readText()
        val error = BufferedReader(InputStreamReader(process.errorStream)).readText()

        file.delete()

        return result.dropLast(1) // drop `\n`
    }

    private object AfterLast : Exception()
}
